[build]
  command = "npm run build"
  publish = "dist/Front-TODOapp/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 